modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="cuisinedelight"
version="${file.jarVersion}" #mandatory
displayName="Cuisine Delight" #mandatory
logoFile="cuisinedelight.png" #optional
logoBlur=false
credits="LightLand Team" #optional
authors="lcy0x1" #optional
description='''
'''
[[dependencies.cuisinedelight]]
    modId="forge"
    mandatory=true
    versionRange="[43.2.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cuisinedelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cuisinedelight]]
    modId="l2library"
    mandatory=true
    versionRange="[1.9.4,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.cuisinedelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.19-1.2.3,)"
    ordering="AFTER"
    side="BOTH"



