modLoader="javafml"
loaderVersion="[46,)"
license="All rights reserved"
[[mods]]
modId="cuisinedelight"
version="${file.jarVersion}" #mandatory
displayName="Cuisine Delight" #mandatory
logoFile="cuisinedelight.png" #optional
logoBlur=false
credits="LightLand Team" #optional
authors="lcy0x1" #optional
description='''
'''
[[dependencies.cuisinedelight]]
    modId="forge"
    mandatory=true
    versionRange="[46.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cuisinedelight]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cuisinedelight]]
    modId="l2library"
    mandatory=true
    versionRange="[2.4.0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.cuisinedelight]]
    modId="farmersdelight"
    mandatory=true
    versionRange="[1.20.1-1.2.2a,)"
    ordering="AFTER"
    side="BOTH"



